import { router } from "expo-router";
import { Pressable, StyleSheet, Switch, Text, View } from "react-native";
import { Card, Button, Title } from "@/components/Ui";
import { PhotoStrip } from "@/components/PhotoStrip";
import { Screen } from "@/components/Screen";
import { effects, filters, stickers } from "@/constants/catalog";
import { themes } from "@/constants/theme";
import { useBoothStore } from "@/store/booth";

const frameColors = ["#f5cc59", "#f19bc2", "#cdebf6", "#d7e7d3", "#e8daf7", "#fbd8ca"];
export default function Style() { const { session, setSession, theme } = useBoothStore(); const p = themes[theme]; const addSticker = (value: string) => setSession({ overlays: [...session.overlays, { id: `${Date.now()}-${value}`, kind: "sticker", value, x: 72, y: 24, scale: 1, rotation: 0, color: p.ink, size: 28 }] }); return <Screen><Title eyebrow="Live canvas" copy="Every edit stays on your phone.">Style your strip</Title><PhotoStrip compact /><Card><Text style={[styles.label, { color: p.ink }]}>Filter</Text><View style={styles.rail}>{filters.map((item) => <Pressable key={item} onPress={() => setSession({ filterId: item })} style={[styles.chip, { borderColor: session.filterId === item ? p.pink : p.ink + "35", backgroundColor: session.filterId === item ? p.surface2 : p.surface }]}><Text style={{ color: p.ink }}>{item}</Text></Pressable>)}</View><Text style={[styles.label, { color: p.ink }]}>Effect</Text><View style={styles.rail}>{effects.map((item) => <Pressable key={item} onPress={() => setSession({ effectId: item })} style={[styles.chip, { borderColor: session.effectId === item ? p.pink : p.ink + "35" }]}><Text style={{ color: p.ink }}>{item}</Text></Pressable>)}</View><Text style={[styles.label, { color: p.ink }]}>Frame color</Text><View style={styles.rail}>{frameColors.map((color) => <Pressable key={color} onPress={() => setSession({ frameColor: color })} style={[styles.color, { backgroundColor: color, borderColor: session.frameColor === color ? p.ink : "transparent" }]} />)}</View><Text style={[styles.label, { color: p.ink }]}>Stickers</Text><View style={styles.rail}>{stickers.map((item) => <Pressable key={item} onPress={() => addSticker(item)} style={[styles.sticker, { borderColor: p.ink + "35" }]}><Text style={{ fontSize: 22 }}>{item}</Text></Pressable>)}</View><View style={styles.toggle}><Text style={{ color: p.ink, fontWeight: "800" }}>WinkBooth branding</Text><Switch value={session.showBranding} onValueChange={(showBranding) => setSession({ showBranding })} trackColor={{ true: p.pink }} /></View><View style={styles.toggle}><Text style={{ color: p.ink, fontWeight: "800" }}>Add date</Text><Switch value={session.showDate} onValueChange={(showDate) => setSession({ showDate })} trackColor={{ true: p.pink }} /></View></Card><Button kind="primary" onPress={() => router.push("/export")}>Export your strip →</Button></Screen>; }
const styles = StyleSheet.create({ label: { fontSize: 13, fontWeight: "900", marginTop: 5 }, rail: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, chip: { minHeight: 44, borderWidth: 1, borderRadius: 12, paddingHorizontal: 11, justifyContent: "center" }, color: { width: 44, height: 44, borderRadius: 22, borderWidth: 3 }, sticker: { width: 44, height: 44, borderWidth: 1, borderRadius: 12, alignItems: "center", justifyContent: "center" }, toggle: { minHeight: 48, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: "#00000020", marginTop: 5 } });
