import { useCallback, useRef, useState } from "react";
import { Alert, Image, Pressable, StyleSheet, Text, View } from "react-native";
import { Camera, useCameraDevice, useCameraPermission, usePhotoOutput } from "react-native-vision-camera";
import * as ImagePicker from "expo-image-picker";
import { router } from "expo-router";
import { layouts, filters } from "@/constants/catalog";
import { themes } from "@/constants/theme";
import { Screen } from "@/components/Screen";
import { Workflow } from "@/components/Workflow";
import { Button, Card, Title } from "@/components/Ui";
import { useBoothStore } from "@/store/booth";

export default function Booth() { const p = themes[useBoothStore((s) => s.theme)]; const { session, setSession } = useBoothStore(); const { hasPermission, requestPermission } = useCameraPermission(); const frontDevice = useCameraDevice("front"); const backDevice = useCameraDevice("back"); const output = usePhotoOutput(); const [cameraOn, setCameraOn] = useState(false); const [facing, setFacing] = useState<"front" | "back">("front"); const device = facing === "front" ? frontDevice : backDevice; const camera = useRef<React.ComponentRef<typeof Camera>>(null); const layout = layouts.find((item) => item.id === session.layoutId) ?? layouts[0];
  const capture = useCallback(async () => { if (!hasPermission) { const ok = await requestPermission(); if (!ok) return Alert.alert("Camera permission needed", "Allow camera access to capture locally."); } if (!cameraOn) return setCameraOn(true); try { const photo = await output.capturePhoto({ flashMode: "off" }, {}); const uri = await photo.saveToTemporaryFileAsync(); photo.dispose(); setSession({ shots: [...session.shots, `file://${uri}`].slice(0, layout.slots.length) }); } catch { Alert.alert("Camera unavailable", "Try reopening the camera or importing a photo."); } }, [cameraOn, hasPermission, layout.slots.length, output, requestPermission, session.shots, setSession]);
  const importPhoto = async () => { const pick = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], quality: 1 }); if (!pick.canceled) setSession({ shots: [...session.shots, pick.assets[0].uri].slice(0, layout.slots.length) }); };
  return <Screen scroll={false}><Workflow /><Title eyebrow="Capture">Start a roll</Title><View style={[styles.camera, { backgroundColor: p.surface2, borderColor: p.ink }]}>{cameraOn && device && hasPermission ? <Camera ref={camera} style={StyleSheet.absoluteFill} device={device} isActive outputs={[output]} /> : <View style={styles.empty}><Text style={[styles.emptyTitle, { color: p.ink }]}>Your roll is ready</Text><Text style={{ color: p.muted }}>Nothing gets uploaded. Everything develops here.</Text></View>}<View style={styles.cameraControls}><Pressable onPress={() => setFacing((v) => v === "front" ? "back" : "front")}><Text style={[styles.control, { backgroundColor: p.ink }]}>Flip</Text></Pressable><Pressable onPress={() => setSession({ mirror: !session.mirror })}><Text style={[styles.control, { backgroundColor: p.ink }]}>Mirror</Text></Pressable></View></View><View style={styles.actions}><Button onPress={capture} kind="primary">◉ {cameraOn ? "Take photo" : "Open camera"}</Button><Button onPress={importPhoto}>Upload</Button></View><Card><Text style={[styles.label, { color: p.ink }]}>Filter</Text><View style={styles.rail}>{filters.map((filter) => <Pressable key={filter} onPress={() => setSession({ filterId: filter })} style={[styles.chip, { borderColor: session.filterId === filter ? p.pink : p.ink + "30", backgroundColor: session.filterId === filter ? p.surface2 : p.surface }]}><Text style={{ color: p.ink }}>{filter}</Text></Pressable>)}</View><Text style={[styles.label, { color: p.ink }]}>Print format</Text><View style={styles.rail}>{layouts.map((item) => <Pressable key={item.id} onPress={() => setSession({ layoutId: item.id, shots: session.shots.slice(0, item.slots.length) })} style={[styles.format, { borderColor: session.layoutId === item.id ? p.pink : p.ink + "30" }]}><Text style={{ color: p.ink, fontWeight: "800" }}>{item.name}</Text><Text style={{ color: p.muted, fontSize: 11 }}>{item.description}</Text></Pressable>)}</View></Card><View style={styles.shots}>{layout.slots.map((_, i) => <View key={i} style={[styles.shot, { backgroundColor: p.surface2 }]}>{session.shots[i] ? <Image source={{ uri: session.shots[i] }} style={StyleSheet.absoluteFill} /> : <Text style={{ color: p.muted }}>{i + 1}</Text>}</View>)}</View><Button kind="primary" disabled={session.shots.length < layout.slots.length} onPress={() => router.push("/style")}>Style your strip →</Button></Screen>; }
const styles = StyleSheet.create({ camera: { height: 330, overflow: "hidden", borderWidth: 2, borderRadius: 22, justifyContent: "center" }, empty: { alignItems: "center", gap: 8, padding: 24 }, emptyTitle: { fontSize: 25, fontFamily: "serif", fontWeight: "800" }, cameraControls: { position: "absolute", bottom: 10, alignSelf: "center", flexDirection: "row", gap: 8 }, control: { color: "white", paddingHorizontal: 13, paddingVertical: 9, borderRadius: 18, fontSize: 12, fontWeight: "800" }, actions: { flexDirection: "row", gap: 10 }, rail: { flexDirection: "row", gap: 8, overflow: "scroll" }, chip: { minHeight: 42, paddingHorizontal: 11, alignItems: "center", justifyContent: "center", borderWidth: 1, borderRadius: 13 }, format: { width: 148, minHeight: 76, padding: 10, borderWidth: 1, borderRadius: 13, gap: 5 }, label: { fontWeight: "800", marginTop: 2 }, shots: { flexDirection: "row", gap: 7 }, shot: { flex: 1, aspectRatio: 1, justifyContent: "center", alignItems: "center", overflow: "hidden", borderRadius: 8 } });
