import { router } from "expo-router";
import { useEffect, useState } from "react";
import { Image, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Button, Card, Title } from "@/components/Ui";
import { Screen } from "@/components/Screen";
import { albums, createAlbum, deletePhoto, initGallery, photos } from "@/services/gallery";
import type { Album, GalleryPhoto } from "@/types/domain";
import { themes } from "@/constants/theme";
import { useBoothStore } from "@/store/booth";

export default function Gallery() { const [items, setItems] = useState<GalleryPhoto[]>([]); const [albumList, setAlbumList] = useState<Album[]>([]); const [name, setName] = useState(""); const p = themes[useBoothStore((s) => s.theme)]; const load = async () => { await initGallery(); setItems(await photos()); setAlbumList(await albums()); }; useEffect(() => { void load(); }, []); const addAlbum = async () => { const trimmed = name.trim(); if (!trimmed) return; await createAlbum(trimmed); setName(""); await load(); }; return <Screen><Title eyebrow="Local memory wall" copy="Nothing is uploaded. Your gallery begins on this device.">Your gallery</Title><View style={styles.gallery}>{items.length ? items.map((item) => <Pressable key={item.id} onLongPress={async () => { await deletePhoto(item); await load(); }} style={[styles.tile, { borderColor: p.ink + "30" }]}><Image source={{ uri: item.thumbnailUri ?? item.imageUri }} style={StyleSheet.absoluteFill} /><View style={[styles.caption, { backgroundColor: p.surface }]}><Text style={{ color: p.ink, fontSize: 11, fontWeight: "800" }}>{new Date(item.createdAt).toLocaleDateString()}</Text></View></Pressable>) : <Card><Text style={{ color: p.muted }}>Your developed rolls will appear here. Long-press a saved roll to remove it from this device.</Text><Button kind="primary" onPress={() => router.push("/(tabs)/booth")}>Start a roll</Button></Card>}</View><Card><Text style={[styles.label, { color: p.ink }]}>Albums</Text><View style={styles.albumRow}>{albumList.map((album) => <View key={album.id} style={[styles.album, { borderColor: p.ink + "30" }]}><Text style={{ color: p.ink, fontWeight: "800" }}>{album.name}</Text></View>)}</View><TextInput value={name} onChangeText={setName} placeholder="New album name" placeholderTextColor={p.muted} style={[styles.input, { color: p.ink, borderColor: p.ink + "40" }]} /><Button onPress={addAlbum}>Create album</Button></Card></Screen>; }
const styles = StyleSheet.create({ gallery: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, tile: { width: "47%", aspectRatio: .72, borderRadius: 12, overflow: "hidden", borderWidth: 1 }, caption: { position: "absolute", left: 0, right: 0, bottom: 0, padding: 7 }, label: { fontSize: 16, fontWeight: "900" }, albumRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, album: { minHeight: 44, borderWidth: 1, borderRadius: 12, paddingHorizontal: 12, justifyContent: "center" }, input: { minHeight: 48, borderWidth: 1, borderRadius: 12, paddingHorizontal: 12, fontSize: 15 } });
